/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import javax.swing.JOptionPane;
/**
 *
 * @author toshiba
 */
public class logOut extends javax.swing.JInternalFrame {

    /**
     * Creates new form logOut
     */
    public logOut() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        rbya = new javax.swing.JRadioButton();
        rbtidak = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(550, 490));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rbya.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rbya);
        rbya.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbya.setForeground(new java.awt.Color(0, 102, 255));
        rbya.setText("YA");
        rbya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbyaActionPerformed(evt);
            }
        });
        getContentPane().add(rbya, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        rbtidak.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rbtidak);
        rbtidak.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbtidak.setForeground(new java.awt.Color(0, 102, 255));
        rbtidak.setText("TIDAK");
        getContentPane().add(rbtidak, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 51, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/IMG_20211125_183837_924.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, -1, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
      if(rbya.isSelected()){
            System.exit(0);
      }
      else if(rbtidak.isSelected()){
          dispose();
      }
      else{
         JOptionPane.showMessageDialog(this, "Anda belum memilih pilihan(YA/TIDAK)");
      }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void rbyaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbyaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbyaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton rbtidak;
    private javax.swing.JRadioButton rbya;
    // End of variables declaration//GEN-END:variables
}
